[application]

# App (Project) Name
name = "sylane-website"

# Dioxus App Default Platform
# desktop, web
default_platform = "web"

# `build` & `serve` dist path
out_dir = "docs"

# resource (assets) file folder
asset_dir = "assets"

[web.app]
# base_path = "sylane-website"
# HTML title tag content
title = "sylane-website"


[web.watcher]

# when watcher trigger, regenerate the `index.html`
reload_html = true

# which files or dirs will be watcher monitoring
watch_path = ["src", "assets" , "md"]

# include `assets` in web platform
[web.resource]

# CSS style file

style = ["css/main.css","css/md.css","css/navbar.css","css/prism.css","css/box.css" ,"css/contacts.css"]

# Javascript code file
script = ["js/prism.js"]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
